app-logic
sinansevgi/mycalculator pull request #5
Opened 2021-08-17 22:30 UTC by sinansevgi

This pull request has calculator logic files. 

Calculate.js is keeps record of data between operations and decide which operation should be done by resolving incoming string.

Operate.js perform mathmatical operations

2021-08-17 23:37 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️

Hi @sinansevgi, you have really done a great job so far, before this milestone is approved, there are a few issues that you need to work on to proceed, but you are almost there! Check my comments below ⬇️  for more details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Kindly submit another review request once done and please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-08-17 23:37 UTC, Elbie-em commented on src/components/App.js
>      </>
- [ ] I noticed that you did not add the calculate.js import. Kindly import calculate.js in your `App` component as required.

2021-08-17 23:37 UTC, Elbie-em commented on README.md
- [ ] I noticed a mixture of `CSS `files with components, kindly create a folder to store your `CSS` files and import them where required.

2021-08-18 07:31 UTC, rindrajosia approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------

2021-08-18 07:50 UTC, merged